#!/bin/bash

#1. 判断参数个数
if [ $# -lt 1 ]
then
    echo 没有足够的参数!
    exit;
fi

#2. 遍历集群所有机器
for host in hadoop100 hadoop101 hadoop102
do
    echo ====================  $host  ====================
    #3. 遍历所有目录，挨个发送
    ssh $host $@
done
    echo "命令已执行完毕！"
